### ISSUE TITLE
gantt_resizer disappear

### ISSUE THREAD

**Issue by ethan666** [DHTMLX/react-gantt-demo#17]
I found the gantt_resizer disappears when I run this project

**Comment by gearcoded** [comment]
Hello,
This demo uses the GPL version. The grid resizer is available in the Pro or Trial version.
We don't have an NPM package with the Pro version. But you can install Gantt as an NPM package the following way:
1) Unpack Gantt to a specific folder, for example, to /opt/gantt_pro
2) Use the following command to install Gantt:
```
npm install /opt/gantt_pro
```

You can read more about installation methods in the following article:
https://docs.dhtmlx.com/gantt/desktop__install_with_bower.html#addingproeditionintoproject
