### ISSUE TITLE
Cannot have multiple gantt in a view

### ISSUE THREAD

**Issue by Kannndev** [DHTMLX/react-gantt-demo#33]
When one Gantt loads another one disappears. Tried having different ids for each instance, still no luck.

**Comment by gearcoded** [comment]
@Kannndev,
I couldn't reproduce the issue in the following demo:
https://files.dhtmlx.com/30d/8c6cfb43ec962418d0422fdca6522aec/react+multiple-gantts-7.1.0-trial.zip
