### ISSUE TITLE
Where does this.ganttContainer get initialized?

### ISSUE THREAD

**Issue by UncleLeoTheDad** [DHTMLX/react-gantt-demo#4]
I have installed and deployed your example app, successfully.  Thanks!

However, as I try to incorporate this example into a working app I have, I keep receiving an error message at this line:
```
componentDidMount() {
	gantt.init(this.ganttContainer); //this line: this.ganttContainer is undefined
	gantt.parse({ data: this.props.state.items});
}
```

I might be missing a react convention or a DHTMLX convention, but I can't see where this is initialized in the working example.  My best guess is that this is somehow translated into this.ganttContainer, but I can't seem to replicate it in my real example:

```html
<div className='gantt-container'>...</div>
```
Any ideas?

**Comment by leojhartiv** [comment]
Figured it out!  I had an error being thrown in my setZoom equivalent method, but it was being swallowed for some reason.  Because of this componentDidMount appeared to be running BEFORE render finished.

**Comment by UncleLeoTheDad** [comment]
Figured it out!  I had an error being thrown in my setZoom equivalent method, but it was being swallowed for some reason.  Because of this componentDidMount appeared to be running BEFORE render finished.  This code in render, initializes this.ganttContainer:
```
render() {
		this.changeScale(this.props.scale.selected); //Code where exception was being thrown

		return (
			<div
				ref={(input) => { this.ganttContainer = input }} //code that intitializes 
				style={{width: '100%', height: '100%'}}>
			</div>
		);
	}
```
