### ISSUE TITLE
TypeScript - getting error - Property 'ganttEventsInitialized' does not exist on type 'GanttStatic'

### ISSUE THREAD

**Issue by georgeneil** [DHTMLX/react-gantt-demo#6]
While trying to implement this demo in typescript I am getting the following error
TS2339: Property 'ganttEventsInitialized' does not exist on type 'GanttStatic'.

Seems like this flag is not available in the type definition
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dhtmlxgantt

**Comment by xzessmedia** [comment]
i can confirm this

**Comment by gearcoded** [comment]
We are aware of the issue that Gantt doesn't have some types included. The dev team will fix it in the future, but I cannot give you any ETA.
However, I couldn't reproduce that issue in the following demo:
https://files.dhtmlx.com/30d/9e7b693971f68966ca9b658e86bf7eda/react+tsx.zip

**Comment by gearcoded** [comment]
@georgeneil and @xzessmedia,
I would like to inform you that the dev team added more types in the 8.0 version:
https://docs.dhtmlx.com/gantt/whatsnew.html#x6629x80x6630x:~:text=Updated%20TypeScript%20type%20definitions
https://docs.dhtmlx.com/gantt/whatsnew.html#x6629x80x6630x:~:text=Type%20definitions%20are%20updated

Now there are types for the tasks, links, grid columns, scales, extensions, and almost everything in the `others` category:
https://docs.dhtmlx.com/gantt/desktop__task_properties.html
https://docs.dhtmlx.com/gantt/desktop__link_properties.html
https://docs.dhtmlx.com/gantt/api__gantt_columns_config.html
https://docs.dhtmlx.com/gantt/api__gantt_scales_config.html
https://docs.dhtmlx.com/gantt/api__gantt_ext_other.html
https://docs.dhtmlx.com/gantt/api__refs__gantt_others.html

You can update to the latest version to get more features and improvements, including the better Typescript Support.

However, even if you are using the older version and don't have plans to upgrade, you can still use the updated version of the `dhtmlxgantt.d.ts` file as the Gantt API is mostly the same:
https://github.com/DHTMLX/gantt/blob/master/codebase/dhtmlxgantt.d.ts

There are still ways to improve, so in the future versions, the dev team will add more types for Gantt.
