### ISSUE TITLE
Extend elements structure

### ISSUE THREAD

**Issue by felipenmoura** [DHTMLX/react-gantt-demo#7]
I would like to be able to extend the html structure.
For example, I want to add an icon to the progress bar that only appears when hovered.
Also, perhaps add something to a date label (like sprint name or an icon).
Would also be very useful to be able to add fields to the sidebar to manage resources (people) or other items.
Is it already possible?

Thanks and keep the good work.

**Comment by AlexKlimenkov** [comment]
Hi,
you can put any html content into task bars or grid cells

https://docs.dhtmlx.com/gantt/desktop__text_block_for_task.html
https://docs.dhtmlx.com/gantt/desktop__specifying_columns.html#datamappingandtemplates
https://docs.dhtmlx.com/gantt/api__gantt_task_text_template.html

E.g.
https://docs.dhtmlx.com/gantt/samples/04_customization/09_html_content.html
https://docs.dhtmlx.com/gantt/samples/04_customization/14_deadline.html

Note that this is a part of javascript API of dhtmlx gantt and these templates live outside React world and work with raw html. Meaning that you can use react components in these templates

**Comment by felipenmoura** [comment]
Hm, awesome...I will give it a try, then, thanks :)
